---
name: "worker"

services:
  api:
    image: videoteam/worke:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    entrypoint: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8009:8000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

